#ifndef WF_FORCED_HOTKEYS_H_
#define WF_FORCED_HOTKEYS_H_

#include "gamepad/GamepadState.h"
#include "enums.pb.h"

/*
 * Locked every boot (TOUCH=A2, START=S2, SELECT=S1). Not FN.
 * D-pad bits go in dpadMask (GAMEPAD_MASK_UP/DOWN/LEFT/RIGHT), not buttonsMask.
 *
 * A2+START+LEFT  = left analog
 * A2+START+RIGHT = right analog
 * A2+START+UP    = digital d-pad
 * A2+SELECT+UP   = SOCD up priority
 * A2+SELECT+LEFT = last input (后输入优先)
 * A2+SELECT+DOWN = SOCD neutral (回中)
 * A2+SELECT+RIGHT = first input (先输入优先)
 */
#define FORCE_GP2040_HOTKEYS 1

#define HOTKEY_01_AUX_MASK 0
#define HOTKEY_01_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S2)
#define HOTKEY_01_DPAD_MASK GAMEPAD_MASK_LEFT
#define HOTKEY_01_ACTION HOTKEY_DPAD_LEFT_ANALOG

#define HOTKEY_02_AUX_MASK 0
#define HOTKEY_02_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S2)
#define HOTKEY_02_DPAD_MASK GAMEPAD_MASK_RIGHT
#define HOTKEY_02_ACTION HOTKEY_DPAD_RIGHT_ANALOG

#define HOTKEY_03_AUX_MASK 0
#define HOTKEY_03_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S2)
#define HOTKEY_03_DPAD_MASK GAMEPAD_MASK_UP
#define HOTKEY_03_ACTION HOTKEY_DPAD_DIGITAL

#define HOTKEY_04_AUX_MASK 0
#define HOTKEY_04_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S1)
#define HOTKEY_04_DPAD_MASK GAMEPAD_MASK_UP
#define HOTKEY_04_ACTION HOTKEY_SOCD_UP_PRIORITY

#define HOTKEY_05_AUX_MASK 0
#define HOTKEY_05_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S1)
#define HOTKEY_05_DPAD_MASK GAMEPAD_MASK_LEFT
#define HOTKEY_05_ACTION HOTKEY_SOCD_LAST_INPUT

#define HOTKEY_06_AUX_MASK 0
#define HOTKEY_06_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S1)
#define HOTKEY_06_DPAD_MASK GAMEPAD_MASK_DOWN
#define HOTKEY_06_ACTION HOTKEY_SOCD_NEUTRAL

#define HOTKEY_07_AUX_MASK 0
#define HOTKEY_07_BUTTONS_MASK (GAMEPAD_MASK_A2 | GAMEPAD_MASK_S1)
#define HOTKEY_07_DPAD_MASK GAMEPAD_MASK_RIGHT
#define HOTKEY_07_ACTION HOTKEY_SOCD_FIRST_INPUT

#define HOTKEY_08_AUX_MASK 0
#define HOTKEY_08_BUTTONS_MASK 0
#define HOTKEY_08_DPAD_MASK 0
#define HOTKEY_08_ACTION HOTKEY_NONE

#define HOTKEY_09_AUX_MASK 0
#define HOTKEY_09_BUTTONS_MASK 0
#define HOTKEY_09_DPAD_MASK 0
#define HOTKEY_09_ACTION HOTKEY_NONE

#define HOTKEY_10_AUX_MASK 0
#define HOTKEY_10_BUTTONS_MASK 0
#define HOTKEY_10_DPAD_MASK 0
#define HOTKEY_10_ACTION HOTKEY_NONE

#define HOTKEY_11_AUX_MASK 0
#define HOTKEY_11_BUTTONS_MASK 0
#define HOTKEY_11_DPAD_MASK 0
#define HOTKEY_11_ACTION HOTKEY_NONE

#define HOTKEY_12_AUX_MASK 0
#define HOTKEY_12_BUTTONS_MASK 0
#define HOTKEY_12_DPAD_MASK 0
#define HOTKEY_12_ACTION HOTKEY_NONE

#define HOTKEY_13_AUX_MASK 0
#define HOTKEY_13_BUTTONS_MASK 0
#define HOTKEY_13_DPAD_MASK 0
#define HOTKEY_13_ACTION HOTKEY_NONE

#define HOTKEY_14_AUX_MASK 0
#define HOTKEY_14_BUTTONS_MASK 0
#define HOTKEY_14_DPAD_MASK 0
#define HOTKEY_14_ACTION HOTKEY_NONE

#define HOTKEY_15_AUX_MASK 0
#define HOTKEY_15_BUTTONS_MASK 0
#define HOTKEY_15_DPAD_MASK 0
#define HOTKEY_15_ACTION HOTKEY_NONE

#define HOTKEY_16_AUX_MASK 0
#define HOTKEY_16_BUTTONS_MASK 0
#define HOTKEY_16_DPAD_MASK 0
#define HOTKEY_16_ACTION HOTKEY_NONE

#endif
