export type GoalId = "keep" | "triple1k" | "wired8k" | "triple8k";

export const goals: { id: GoalId; label: string; hint: string }[] = [
  {
    id: "keep",
    label: "继续 GP2040-CE 有线 1k",
    hint: "保留现有固件与主机认证",
  },
  {
    id: "triple1k",
    label: "蓝牙 / 2.4G / 有线三模 · 1k",
    hint: "PC 向产品，主机认证要另做",
  },
  {
    id: "wired8k",
    label: "有线 8k",
    hint: "必须 USB High Speed 芯片",
  },
  {
    id: "triple8k",
    label: "三模 8k",
    hint: "新项目，不是改 GP2040-CE",
  },
];

export type Board = {
  name: string;
  mcu: string;
  usb: "FS" | "HS";
  radio: string;
  wiredHz: string;
  btHz: string;
  g24Hz: string;
  goals: GoalId[];
  buy: string;
  note: string;
  pick?: boolean;
};

export const boards: Board[] = [
  {
    name: "你现有的 G2 / RUYI / doio / Pico16 等",
    mcu: "RP2040",
    usb: "FS",
    radio: "无",
    wiredHz: "1 kHz 上限",
    btHz: "无",
    g24Hz: "无",
    goals: ["keep"],
    buy: "已量产",
    note: "固件资产都在这套板上。PS5 / Xbox USB 认证走 PIO-USB 从口，换芯片等于重做产品。",
    pick: true,
  },
  {
    name: "Raspberry Pi Pico / Pico 2",
    mcu: "RP2040 / RP2350",
    usb: "FS",
    radio: "无",
    wiredHz: "1 kHz 上限",
    btHz: "无",
    g24Hz: "无",
    goals: ["keep"],
    buy: "极易买到",
    note: "RP2350 更快、RAM 更大，USB 仍然是 Full Speed，8k 做不到。",
  },
  {
    name: "Raspberry Pi Pico W / Pico 2 W",
    mcu: "RP2040/RP2350 + CYW43439",
    usb: "FS",
    radio: "Wi-Fi + BT Classic / BLE",
    wiredHz: "1 kHz",
    btHz: "约 80–250 Hz，抖动大",
    g24Hz: "无专用 2.4G 协议",
    goals: ["keep"],
    buy: "极易买到",
    note: "GP2040-CE 完全没用 CYW43439。能塞进 BTstack HID，但不适合格斗：间隔不稳，也没有 2.4G 接收器方案。",
  },
  {
    name: "Seeed XIAO nRF52840",
    mcu: "nRF52840",
    usb: "FS",
    radio: "BLE 5 + Nordic ESB 2.4G",
    wiredHz: "1 kHz",
    btHz: "标准 HID 约 125 Hz；私有协议可冲 1 kHz",
    g24Hz: "ESB 轻松 1 kHz",
    goals: ["triple1k"],
    buy: "淘宝 / Seeed，体积极小",
    note: "单芯片三模 1k 的首选评估板。USB 仍是 Full Speed，8k 不可能。适合先验证射频，再画自己的 PCB。",
    pick: true,
  },
  {
    name: "Nordic nRF52840 DK",
    mcu: "nRF52840",
    usb: "FS",
    radio: "BLE 5 + ESB / Gazell 2.4G",
    wiredHz: "1 kHz",
    btHz: "同 XIAO",
    g24Hz: "1 kHz 稳定，冲 4–8k 很紧",
    goals: ["triple1k"],
    buy: "官方 DK，调试方便",
    note: "Segger 调试、天线完整，做协议比 XIAO 省事。量产再缩成自己的板。",
  },
  {
    name: "Nice!Nano v2",
    mcu: "nRF52840",
    usb: "FS",
    radio: "BLE + ESB",
    wiredHz: "1 kHz",
    btHz: "同 XIAO",
    g24Hz: "1 kHz",
    goals: ["triple1k"],
    buy: "客制化圈常见",
    note: "Pro Micro 脚位，方便插到现有格斗板转接。电池充电电路现成。",
  },
  {
    name: "ESP32-S3-DevKitC-1 / XIAO ESP32-S3",
    mcu: "ESP32-S3",
    usb: "FS",
    radio: "BLE 5 + Wi-Fi / ESP-NOW",
    wiredHz: "1 kHz",
    btHz: "BLE HID 约 100–250 Hz",
    g24Hz: "ESP-NOW 可做 1 kHz 级私有 2.4G",
    goals: ["triple1k"],
    buy: "极便宜",
    note: "社区（Bluepad32）成熟，但 BLE 只有 BLE 没有经典蓝牙。用 ESP-NOW 当 2.4G 要自己写接收器固件。PS5 认证没有现成栈。",
  },
  {
    name: "Teensy 4.1",
    mcu: "NXP i.MX RT1062",
    usb: "HS",
    radio: "无",
    wiredHz: "8 kHz 已有实锤",
    btHz: "无",
    g24Hz: "无",
    goals: ["wired8k"],
    buy: "PJRC / 国内代理",
    note: "USB High Speed 片上 PHY，开源项目已跑过 8 kHz HID。这是评估「有线 8k 到底有没有手感」最快的一块板。",
    pick: true,
  },
  {
    name: "WeAct MiniSTM32H743",
    mcu: "STM32H743VIT6",
    usb: "HS",
    radio: "无",
    wiredHz: "8 kHz 可达",
    btHz: "无",
    g24Hz: "无",
    goals: ["wired8k"],
    buy: "WeAct，便宜",
    note: "片上 HS PHY，不必外挂 USB3300。不要买 STM32H723：那颗只有 Full Speed。",
  },
  {
    name: "沁恒 CH32V307V-EVT",
    mcu: "CH32V307",
    usb: "HS",
    radio: "无",
    wiredHz: "8 kHz 可达",
    btHz: "无",
    g24Hz: "无",
    goals: ["wired8k"],
    buy: "国内最便宜的 HS MCU 之一",
    note: "USB 2.0 HS 内置 PHY。生态是 MounRiver / WCH SDK，不是 Pico SDK，GP2040-CE 迁不过去。",
  },
  {
    name: "Arduino Giga R1 WiFi",
    mcu: "STM32H747",
    usb: "HS",
    radio: "板载 Murata 模组（Wi-Fi/BLE，不适合当手柄射频）",
    wiredHz: "8 kHz 可达",
    btHz: "不当手柄用",
    g24Hz: "无",
    goals: ["wired8k"],
    buy: "Arduino 现货",
    note: "双核 H7 + HS USB，适合当 8k 有线原型。板载无线不要指望拿来做低延迟手柄。",
  },
  {
    name: "乐鑫 ESP32-P4 Function EV",
    mcu: "ESP32-P4",
    usb: "HS",
    radio: "本身无射频，常配 ESP32-C6 子板",
    wiredHz: "8 kHz 理论上可以",
    btHz: "靠 C6 陪绑",
    g24Hz: "靠 C6 / ESP-NOW",
    goals: ["wired8k", "triple8k"],
    buy: "官方套件",
    note: "少见的「USB HS + 可配无线」组合。固件栈很新，格斗手柄生态几乎为零，只适合预研。",
  },
  {
    name: "双 MCU：RP2040 + XIAO nRF52840",
    mcu: "RP2040 + nRF52840",
    usb: "FS",
    radio: "BLE + ESB 2.4G",
    wiredHz: "1 kHz（仍走 GP2040-CE）",
    btHz: "1 kHz 级私有 / 标准 HID 较低",
    g24Hz: "1 kHz",
    goals: ["keep", "triple1k"],
    buy: "两块现成板用 UART 连",
    note: "对你最现实：有线继续 GP2040-CE（含 PS5 USB 认证），无线交给 nRF。不要拆现有固件重写。",
    pick: true,
  },
  {
    name: "双 MCU：Teensy 4.1 + nRF52840 DK",
    mcu: "i.MX RT1062 + nRF52840",
    usb: "HS",
    radio: "BLE + ESB",
    wiredHz: "8 kHz",
    btHz: "标准 HID 远低于 8k",
    g24Hz: "要 8k 必须私有协议，接收器也得是 USB HS",
    goals: ["triple8k", "wired8k"],
    buy: "两块评估板",
    note: "这才是「三模 8k」的最低硬件门槛。接收器不能用普通 nRF USB，必须再做一块 HS USB 接收器。等于新产品。",
  },
];

export const customBoards = [
  "14PNEW",
  "17P",
  "17PNT",
  "d26",
  "doio",
  "G2",
  "G2G",
  "G4F",
  "G5F",
  "HaM",
  "hnu",
  "Pico16",
  "Pico16N",
  "Pico19",
  "QF",
  "QFG",
  "RUYI",
];

export const inputModes = [
  "XInput",
  "Xbox One",
  "PS3 / PS4 / PS5",
  "Switch / Switch Pro",
  "Keyboard",
  "HID",
  "Xbox OG",
  "迷你机（MD / PCE / NeoGeo / Astro / Egret）",
];
