[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.cdc_on_boot = 0
board_build.f_cpu = 240000000L
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DUSE_NIMBLE
  -DWF_ENABLE_BLE=1
  -I../include
  -I../../../wireless
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
  lemmingDev/ESP32-BLE-Gamepad@^0.5.6
