add_subdirectory(14PNEW)
add_subdirectory(17P)
add_subdirectory(17PNT)
add_subdirectory(d26)
add_subdirectory(doio)
add_subdirectory(G2)
add_subdirectory(G2G)
add_subdirectory(G4F)
add_subdirectory(G5F)
add_subdirectory(HaM)
add_subdirectory(hnu)
add_subdirectory(Pico16)
add_subdirectory(Pico16N)
add_subdirectory(Pico19)
add_subdirectory(QF)
add_subdirectory(QFG)
add_subdirectory(RUYI)
