[env:esp32-c3-module]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 160000000L
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -Iinclude
  -I../../wireless
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
